apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-egress-internet
spec:
  endpointSelector: {}
  egress:
    - toCIDR:
        - 0.0.0.0/0
  enableDefaultDeny:
    egress: false
    ingress: false
